apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-k8s-dungtv
spec:
  selector:
    matchLabels:
      app: nestjs-k8s-dungtv
  replicas: 2
  template:
    metadata:
      labels:
        app: nestjs-k8s-dungtv
    spec:
      containers:
        - name: nestjs-k8s-dungtv
          image: trandung2001/nestjs-k8s
          ports:
            - containerPort: 3000
